# Generated by Django 5.1.6 on 2025-02-12 12:04

import django.db.models.deletion
import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Custom name for a photo', max_length=255)),
                ('filename', models.CharField(help_text='Original filename of the uploaded file', max_length=255)),
                ('image', models.ImageField(help_text='Image path', upload_to=photos.models.Photo.upload_to)),
                ('status', models.IntegerField(choices=[(photos.models.Photo.Status['TRACKED'], 'TRACKED'), (photos.models.Photo.Status['LOST'], 'LOST'), (photos.models.Photo.Status['DUPLICATED'], 'DUPLICATED')], default=photos.models.Photo.Status['TRACKED'], help_text='State of a file detected by a system')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when photo was uploaded to a system')),
                ('category', models.ForeignKey(blank=True, help_text='Category that photo belongs to', null=True, on_delete=django.db.models.deletion.RESTRICT, to='photos.category')),
            ],
        ),
    ]
