# Generated by Django 5.1.6 on 2025-02-12 08:56

import django.db.models.deletion
import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=photos.models.upload_to)),
                ('status', models.IntegerField(choices=[(photos.models.PhotoStatus['TRACKED'], 'TRACKED'), (photos.models.PhotoStatus['LOST'], 'LOST'), (photos.models.PhotoStatus['DUPLICATED'], 'DUPLICATED')], default=photos.models.PhotoStatus['TRACKED'])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photos.category')),
            ],
        ),
    ]
