# Generated by Django 5.1.6 on 2025-02-12 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category that photo belongs to', null=True, on_delete=django.db.models.deletion.RESTRICT, to='photos.category'),
        ),
    ]
