# Generated by Django 5.1.6 on 2025-02-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='E:\\Programowanie\\Python\\Django\\Photos\\project\\media'),
        ),
    ]
